{{- if and .Values.appSecrets.create (not .Values.appSecrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "healthcabinet.appSecretName" . }}
  labels:
    {{- include "healthcabinet.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $k, $v := .Values.appSecrets.data }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
