{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  labels:
    {{- include "healthcabinet.labels" . | nindent 4 }}
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
    - name: http
      protocol: HTTP
      port: {{ .Values.gateway.listeners.httpPort }}
      allowedRoutes:
        namespaces:
          from: Same
    {{- if .Values.gateway.tls.enabled }}
    - name: https
      protocol: HTTPS
      port: {{ .Values.gateway.listeners.httpsPort }}
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: {{ .Values.gateway.tls.certManager.secretName }}
      allowedRoutes:
        namespaces:
          from: Same
    {{- end }}
{{- end }}
